# SESSION 1: NEURAL NETWORK PROGRAMMING

## Overview and objectives 
    Connect the abstract idea of a neural network with the concrete tools used to implement, train and evaluate AI models, and get experience with standard pipeline.

    By the end of this session you will be able to:
    - Understand basics of abstraction behind neural networks: Layers, activations, parameters and predictions.
    - Why neural networks became so successful.
    - Build and train simple models in keras, using standard ML pipeline.
    - Model complexity and data representation.
    - Identify common neural architecture for tabular data, images and time series.


# Neural Network abstraction

- Neural networks are a very popular family of ML models.
- Conceptually, ensemble of logistic regression models.

<img width="50%" src="https://deeplearningmath.org/images/shallow_NN.png"/>

## Neural Networks — Compact Summary

Neural networks are models inspired by how biological neurons work.

Conceptually, they can be seen as:

```text
many logistic regressions connected to each other
```

Each artificial neuron performs a similar operation to:

where:

- `x` = inputs
- `w` = learned weights
- `b` = bias
- `σ` = activation function (for example sigmoid or ReLU)

---

## Main idea

A simple logistic regression:

- learns simple patterns,
- linear separations,
- basic classification problems.

A neural network:

- combines MANY neurons,
- organizes neurons into layers,
- learns complex, non-linear patterns.

---

## Typical architecture

```text
Input Layer
    ↓
Hidden Layers
    ↓
Output Layer
```

Each layer learns more abstract representations.

Example in computer vision:

```text
edges → shapes → objects → faces
```

---

## Why are they so powerful?

Because they can learn:

- images
- voice
- text
- natural language
- complex predictions
- generative models

---

## Final idea

```text
A neural network = many small logistic regressions working together in several layers to learn complex patterns.
```
### Connectionist model built from complex interactions of simple units

- **Basic Model**: Multi-layer perceptron (MLP). Dense connections of units across multiple layers:
    - **Neurons**: Basic units that receive input, process it and pass the output.
    - **Input layers**: Where data enters.
    - **Hidden Layers**: Intermediate layers where computation happenns.
    - **Output Layer**: Final layer that outputs results.
-**Activation Function**: Determinates the output of neurons; common functions like sigmoid, Tanh, ReLu.


## WHY SO POPULAR?
- Convolutional Neural Network achieved a significant improvement over state of the art image classifiers.
- CNNs can be seen as MLPs with sparse connections and weight sharing.



# Why are CNNs so popular?

A CNN (Convolutional Neural Network) is a neural network specialized in images.

Instead of analyzing the whole image at once like a normal MLP, a CNN looks at small regions and detects patterns such as:

- edges
- shapes
- textures

## Main ideas

### Convolution
Small filters move across the image searching for patterns.

### Weight Sharing
The same filter is reused across the entire image, reducing the number of parameters.

### Pooling
The image size is reduced while keeping the most important information.

## Why was it revolutionary?

CNNs:
- need fewer parameters than traditional neural networks
- are more efficient
- learn visual features automatically
- achieved huge improvements in image classification

## Simple pipeline

Image → Convolution → Pooling → Dense layers → Prediction

Example:
- detects edges
- then shapes
- then objects
- finally predicts: “cat”, “dog”, “car”, etc.

## Advantages:
- **Hardware friendly:** Regular structures, well suited for optimization (tensor based computations, parallelization)
- **Scalability**: Hugu models on huge datasets (trillions of parameters over TBs of data).
- **Manage unstructured data**: Can extract from audio and images

## Disavantages:
- **Data hungry**: Their benefits are seen only on extremely Large datasets.
- **Black Boxes**: Predictions cannot be explained or interpreted. Pontential unexpected behaviors. No guarantees.
- **Poor handling of discontinuities**: Smoothness is assumed in the feature space and output. Difficulties with discrete problems.


## BUILDING NEURAL NETWORKS IN PRACTICE
- frameworks: Matlab, Torch, Keras, JAX...
### Modern AI Frameworks Summary

Modern AI frameworks converged around two key ideas:

- Tensor operations similar to NumPy
- Automatic differentiation for training neural networks

### Keras 3.0

Keras 3.0 became a multi-backend framework focused on:
- simplicity
- speed
- flexibility
#### What is Keras?

Keras is a simple Python library used to build and train neural networks.

It provides an easy and clean API for creating AI models without implementing all the mathematics manually.

Keras can run on top of:
- TensorFlow
- JAX
- PyTorch

Simple analogy:
- TensorFlow/JAX/PyTorch → engine
- Keras → easy-to-use interface

#### Main Features

- Modular API based on:
  - Models
  - Layers
  - Optimizers
  - Loss functions

- Compatible with:
  - TensorFlow
  - PyTorch
  - JAX

- Same model can run on:
  - CPU
  - GPU
  - TPU

with minimal code changes, even in distributed systems.

### 1. Tensor operations following the NumPy API

Frameworks use tensors with operations very similar to NumPy.

A tensor can be:
- a number
- a vector
- a matrix
- or multidimensional data

Example in NumPy:

```python
import numpy as np

x = np.array([1,2,3])
y = x * 2
```

AI frameworks work similarly, but optimized for GPUs and large-scale computation.

Example:

```python
x = tensor([1,2,3])
y = x * 2
```

The goal is:
> perform mathematical operations efficiently using tensor-based computation.

---

### 2. Automatic differentiation for gradient-based optimization

Neural networks learn by adjusting weights to reduce error.

To know how to update those weights, the framework computes derivatives (gradients).

Modern frameworks calculate these gradients automatically using backpropagation.

Example:

```python
loss.backward()
```

The framework automatically:
- computes derivatives
- propagates errors
- updates weights during training

---

### Simple Summary

Modern AI frameworks are mainly built around:

- fast tensor operations similar to NumPy
- automatic gradient computation for training neural networks


# 1. First Neural-Network example in Keras:
## "Hello World of ML:" Classifying the Iris Dataset
- Example of how NNs are also suitable for feature-based classification.

In [0]:
import os #let you work with os
os.environ["KERAS_BACKEND"] = "jax" #tells keras to use JAX as intern engine
os.environ["JAX_PLATAFORMS"] = "cpu" #use cpu to calculate


In [0]:
# Install libraries
%pip install keras jax jaxlib

# Set Keras backend BEFORE importing keras
import os
os.environ["KERAS_BACKEND"] = "jax"

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Figure settings
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['figure.dpi'] = 90

import seaborn as sns
sns.set_theme()

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Import standalone Keras
import keras

# Optional verification
import keras.backend as K
print(K.backend())

In [0]:
import os
os.environ["KERAS_BACKEND"] = "jax"

import keras
import jax

print(jax.devices())

import keras.backend as K
print(K.backend())

In [0]:
iris = load_iris()
X = iris.data
y = iris.target
print(iris.DESCR)
print(type(iris))


Exploring Data

In [0]:
print(iris.keys()) #Iris is a dictionary

print("features names: \n")
print(iris.feature_names)


print("Iris Data: \n")
print(iris.data[:5])

print("Target names: \n")
print(iris.target_names)

print("Target: \n")
print(iris.target)

In [0]:
# Splitting data to train/test


x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 42)
print("x_train before scaler: \n",x_train[:5])
print("\n")
print("x_test before scaler: \n",x_test[:5])

scaler = StandardScaler() # Normalize the data to give the same scale to all the features
x_train = scaler.fit_transform(x_train) #Use the scaler to normalize the data, fit learns the mean and std of the data and transform the data
x_test = scaler.transform(x_test)
print("\n")
print("x_train after scaler: \n",x_train[:5])
print("\n")
print("x_test after scaler: \n",x_test[:5])



In [0]:
#CREATE THE MODEL
model1 = keras.models.Sequential( #Secuential model
    [
        keras.layers.Input(shape=(4,)), #Each data has 4 features

        #First hidden layer with 2 neurons, relu let the positive values and set the negative to zero
        keras.layers.Dense(2, activation = 'relu'),

        #Second hidden layer with 6 neurons, increase the number of neurons to increase the complexity
        keras.layers.Dense(6, activation = 'relu'),

        #Third layer with 3 neurons, softmax is used for multiclass classification, it will return a probability for each class
        keras.layers.Dense(3, activation = 'softmax')
    ]
)

# Compile the way the model will be trained
model1.compile(optimizer='adam', #algorithm to minimize the loss function
               loss = 'sparse_categorical_crossentropy', #error function to classification when labels are integers
               metrics = ['accuracy']) # metric to evaluate the % of correct predictions

# Print the architecture of the model
model1.summary()


In [0]:
# Fit the model and see the trainig behavior
#fit means adjust the weights to minimize the loss function
# epoch means how many times the model will see the data
# batch_size means how many data will be used to adjust the weights each epoch 
history1 = model1.fit(x_train, y_train, epochs = 50, batch_size = 5, validation_split = 0.2)

In [0]:
# Loss is the error function, the lower the better
# val_loss is the error function on the validation set, the lower the better
# val_accuracy is the accuracy on the validation set

plt.plot(history1.history['loss'], label = 'Loss')
plt.plot(history1.history['val_loss'], label = 'Validation Loss')
plt.legend()
plt.show()

In [0]:
#evaluate the model with data that the model has not seen
y_pred_probs = model1.predict(x_test)
print("y_pred_probs: \n", y_pred_probs[:5])
print("\n")
# y_pred is the predicted class
y_pred = np.argmax(y_pred_probs,axis=1)
print("y_pred: \n", y_pred[:5])
print("\n")

print("Accurancy on test set:", accuracy_score(y_test, y_pred))
print("Classification report: \n", classification_report(y_test, y_pred))

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix: \n", conf_matrix)

# Accuracy global

```text
Accuracy on test set: 0.9111111111111111
```

Significa:

\[
91.1\%
\]

de las muestras de test fueron clasificadas correctamente.

---

# ¿Cuántos ejemplos había?

```text
support = 45
```

Tenías:
- 45 flores en test.

Entonces:

\[
45 \times 0.911 \approx 41
\]

≈ 41 clasificadas correctamente.

---

# Classification Report

## Clase 0

```text
precision = 1.00
recall = 1.00
f1-score = 1.00
support = 19
```

La clase 0 se clasificó perfectamente.

---

## ¿Qué significa Precision?

\[
\text{Precision} =
\frac{TP}{TP+FP}
\]

Pregunta:

> “Cuando el modelo predice clase 0, ¿cuántas veces acierta?”

- 1.00 = 100%

---

## ¿Qué significa Recall?

\[
\text{Recall} =
\frac{TP}{TP+FN}
\]

Pregunta:

> “De todas las flores realmente clase 0, ¿cuántas encontró?”

- También 100%

---

# Clase 1

```text
precision = 0.76
recall = 1.00
```

Interpretación:

- Detecta TODAS las clase 1.
- Pero a veces confunde otras clases como clase 1.

---

# Clase 2

```text
precision = 1.00
recall = 0.69
```

Interpretación:

- Cuando predice clase 2 suele acertar.
- PERO se le escapan bastantes clase 2.

---

# Confusion Matrix

```text
[[19  0  0]
 [ 0 13  0]
 [ 0  4  9]]
```

Esto es una de las herramientas más importantes en clasificación.

---

# Cómo se lee

- Filas → clase real
- Columnas → clase predicha

---

# Primera fila

```text
[19 0 0]
```

Clase real 0:

| Predijo 0 | Predijo 1 | Predijo 2 |
|---|---|---|
| 19 | 0 | 0 |

Perfecto.

---

# Segunda fila

```text
[0 13 0]
```

Clase real 1:

| Predijo 0 | Predijo 1 | Predijo 2 |
|---|---|---|
| 0 | 13 | 0 |

Perfecto también.

---

# Tercera fila

```text
[0 4 9]
```

Clase real 2:

| Predijo 0 | Predijo 1 | Predijo 2 |
|---|---|---|
| 0 | 4 | 9 |

Aquí está el problema:

- 4 flores clase 2
- fueron confundidas con clase 1.

---

# Conclusión real del modelo

La red neuronal:

- separa MUY bien la clase 0,
- separa bien la clase 1,
- pero tiene dificultades distinguiendo:

\[
\text{clase 1 vs clase 2}
\]

---

# ¿Por qué ocurre esto en Iris?

Porque:

- `setosa` es muy separable,
- `versicolor` y `virginica` son más parecidas entre sí.